# Generated by Django 2.1.11 on 2020-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
