# Generated by Django 2.1.11 on 2020-03-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_permission_is_accessible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
