# Generated by Django 2.1.11 on 2020-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_user_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitygroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this entity group should be treated as active. Unselect this instead of deleting groups.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this permission should be treated as active. Unselect this instead of deleting permission.', verbose_name='active'),
        ),
    ]
