# Generated by Django 2.1.11 on 2020-05-19 01:09

import access_control.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_auto_20200428_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='codename')),
                ('workspace_id', models.CharField(max_length=36, verbose_name='workspaceId')),
                ('report_id', models.CharField(max_length=36, verbose_name='reportId')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this report should be treated as active. Unselect this instead of deleting report.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
            managers=[
                ('objects', access_control.models.ReportManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'report category',
                'verbose_name_plural': 'report categories',
            },
            managers=[
                ('objects', access_control.models.ReportCategoryManager()),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.ReportCategory'),
        ),
        migrations.AddField(
            model_name='report',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.Entity'),
        ),
        migrations.AddField(
            model_name='report',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.Permission'),
        ),
    ]
