# Generated by Django 2.1.11 on 2020-05-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_auto_20200519_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_selected_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_selected_entity', to='access_control.Entity'),
        ),
    ]
